# Generated by Django 5.0.1 on 2024-02-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_life', models.IntegerField(default=40)),
                ('p2_life', models.IntegerField(default=40)),
            ],
        ),
    ]
